wandb_version: 1

image_size:
  desc: null
  value:
  - 512
  - 512
batch_size:
  desc: null
  value: 4
num_workers:
  desc: null
  value: 0
num_epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.0001
device:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1731737700.0
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      - 105
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      - 105
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
